### PR TITLE
Bump HatchPreviewer to latest release

### PR DESCRIPTION
**Pull request by manuq**
A npm dependency was added so I re-generated the json with sources.

### CODE REVIEW

**Comment by nedrichards** [comment]
@manuq you can run a test build (visible at https://flathub.org/builds) by typing a comment that says bot, build

**Comment by manuq** [comment]
bot, build

**Comment by manuq** [comment]
@nedrichards build succeed: https://flathub.org/builds/#/builders/2/builds/3578

**Comment by nedrichards** [comment]
If it works then you're good to merge. I assume you tested it as you're upstream!

**Pull request merged**
